# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.11.0
    hooks:
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4']
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
    -   id: ruff
        args: [--fix, --show-fixes, --format, grouped]
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    # TODO: clean up these old scripts
    hooks:
    -   id: shellcheck
        exclude: ^(deployment/scripts/|deployment/overlay/scripts|deployment/nci/templates)
-   repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
    -   id: pip-compile
