name: base
channels:
-   conda-forge
-   defaults
dependencies:
-   _libgcc_mutex=0.1=conda_forge
-   _openmp_mutex=4.5=2_kmp_llvm
-   affine=2.3.0=pyhd3eb1b0_0
-   aom=3.8.1=h59595ed_0
-   archspec=0.2.3=pyhd8ed1ab_0
-   attrs=23.1.0=py311h06a4308_0
-   aws-c-auth=0.7.16=h79b3bcb_6
-   aws-c-cal=0.6.10=hb29e0c7_1
-   aws-c-common=0.9.13=hd590300_0
-   aws-c-compression=0.2.18=hecc5fa9_1
-   aws-c-event-stream=0.4.2=hf9b2f7b_4
-   aws-c-http=0.8.1=h5d7533a_5
-   aws-c-io=0.14.5=h50678d4_1
-   aws-c-mqtt=0.10.2=hf479d2b_4
-   aws-c-s3=0.5.2=h4ad9680_0
-   aws-c-sdkutils=0.1.15=hecc5fa9_1
-   aws-checksums=0.1.18=hecc5fa9_1
-   aws-crt-cpp=0.26.2=h19f5d62_7
-   aws-sdk-cpp=1.11.267=h5606698_1
-   azure-core-cpp=1.11.1=h91d86a7_1
-   azure-storage-blobs-cpp=12.10.0=h00ab1b0_1
-   azure-storage-common-cpp=12.5.0=h94269e2_4
-   blas=1.0=mkl
-   blosc=1.21.5=h0f2a231_0
-   boltons=23.0.0=py311h06a4308_0
-   boost-cpp=1.82.0=hdb19cb5_2
-   bottleneck=1.3.7=py311hf4808d0_0
-   brotli=1.0.9=he6710b0_2
-   brotlipy=0.7.0=py311h5eee18b_1002
-   brunsli=0.1=h2531618_0
-   bzip2=1.0.8=h7b6447c_0
-   c-ares=1.27.0=hd590300_0
-   c-blosc2=2.12.0=h80c7b02_0
-   ca-certificates=2024.2.2=hbcca054_0
-   cached-property=1.5.2=py_0
-   cairo=1.18.0=h3faef2a_0
-   certifi=2024.2.2=py311h06a4308_0
-   cffi=1.15.1=py311h5eee18b_3
-   cfitsio=4.3.1=hbdc6101_0
-   cftime=1.6.2=py311hbed6279_0
-   charls=2.4.2=h59595ed_0
-   charset-normalizer=2.0.4=pyhd3eb1b0_0
-   click=8.1.7=py311h06a4308_0
-   click-plugins=1.1.1=pyhd3eb1b0_0
-   cligj=0.7.2=pyhd3eb1b0_0
-   cloudpickle=2.2.1=py311h06a4308_0
-   conda=23.5.2=py311h06a4308_0
-   conda-content-trust=0.2.0=py311h06a4308_0
-   conda-libmamba-solver=23.7.0=py311h06a4308_0
-   conda-package-handling=2.2.0=pyh38be061_0
-   conda-package-streaming=0.9.0=pyhd8ed1ab_0
-   cryptography=42.0.2=py311hdda0065_0
-   cython=3.0.8=py311h5eee18b_0
-   dav1d=1.2.1=h5eee18b_0
-   distro=1.9.0=pyhd8ed1ab_0
-   expat=2.5.0=h6a678d5_0
-   fmt=10.2.1=h00ab1b0_0
-   font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
-   font-ttf-inconsolata=2.001=hcb22688_0
-   font-ttf-source-code-pro=2.030=hd3eb1b0_0
-   font-ttf-ubuntu=0.83=h8b1ccd4_0
-   fontconfig=2.14.2=h14ed4e7_0
-   fonts-anaconda=1=h8fa9717_0
-   fonts-conda-ecosystem=1=hd3eb1b0_0
-   freetype=2.12.1=h4a9f257_0
-   freexl=2.0.0=hf309648_0
-   gdal=3.8.4=py311h8be719e_0
-   geos=3.12.1=h59595ed_0
-   geotiff=1.7.1=h6b2125f_15
-   giflib=5.2.1=h5eee18b_3
-   h5py=3.10.0=nompi_py311hebc2b07_101
-   hdf4=4.2.15=h2a13503_7
-   hdf5=1.14.3=nompi_h4f84152_100
-   hdf5-external-filter-plugins-bitshuffle=0.1.0=h6bc1b1d_12
-   hdf5plugin=4.4.0=py311h28d1a1f_0
-   icu=73.2=h59595ed_0
-   idna=3.4=py311h06a4308_0
-   imagecodecs=2024.1.1=py311h089f87a_0
-   imageio=2.33.1=py311h06a4308_0
-   iniconfig=1.1.1=pyhd3eb1b0_0
-   intel-openmp=2023.1.0=hdb19cb5_46306
-   joblib=1.2.0=py311h06a4308_0
-   json-c=0.17=h7ab15ed_0
-   jsonpatch=1.32=pyhd3eb1b0_0
-   jsonpointer=2.1=pyhd3eb1b0_0
-   jxrlib=1.1=h7b6447c_2
-   kealib=1.5.3=h2f55d51_0
-   keyutils=1.6.1=h166bdaf_0
-   krb5=1.21.2=h659d440_0
-   lazy_loader=0.3=py311h06a4308_0
-   lcms2=2.16=hb7c19ff_0
-   ld_impl_linux-64=2.38=h1181459_1
-   lerc=4.0.0=h27087fc_0
-   libabseil=20240116.1=cxx17_h59595ed_2
-   libaec=1.1.2=h59595ed_1
-   libarchive=3.7.2=h2aa1ff5_1
-   libavif16=1.0.4=h1dcd450_1
-   libboost=1.82.0=h109eef0_2
-   libbrotlicommon=1.1.0=hd590300_1
-   libbrotlidec=1.1.0=hd590300_1
-   libbrotlienc=1.1.0=hd590300_1
-   libcrc32c=1.1.2=h6a678d5_0
-   libcurl=8.5.0=hca28451_0
-   libdeflate=1.19=hd590300_0
-   libedit=3.1.20221030=h5eee18b_0
-   libev=4.33=h7f8727e_1
-   libexpat=2.5.0=hcb278e6_1
-   libffi=3.4.4=h6a678d5_0
-   libgcc-ng=13.2.0=h807b86a_5
-   libgdal=3.8.4=h9323651_0
-   libgfortran-ng=13.2.0=h69a702a_5
-   libgfortran5=13.2.0=ha4646dd_5
-   libglib=2.78.4=hdc74915_0
-   libgoogle-cloud=2.21.0=h72bcb37_2
-   libgoogle-cloud-storage=2.21.0=hc7a4891_2
-   libgrpc=1.61.1=h42401df_1
-   libiconv=1.17=hd590300_2
-   libjpeg-turbo=3.0.0=hd590300_1
-   libkml=1.3.0=h096b73e_7
-   libmamba=1.5.1=had39da4_2
-   libmambapy=1.5.1=py311hf2555c7_2
-   libnetcdf=4.9.2=nompi_h9612171_113
-   libnghttp2=1.58.0=h47da74e_1
-   libnsl=2.0.1=hd590300_0
-   libpng=1.6.43=h2797004_0
-   libpq=16.2=h33b98f1_0
-   libprotobuf=4.25.2=h08a7969_1
-   libre2-11=2023.09.01=h5a48ba9_2
-   librttopo=1.1.0=h8917695_15
-   libsolv=0.7.28=hfc55251_0
-   libspatialite=5.1.0=h7bd4643_4
-   libsqlite=3.45.1=h2797004_0
-   libssh2=1.11.0=h0841786_0
-   libstdcxx-ng=13.2.0=h7e041cc_5
-   libtiff=4.6.0=ha9c0a0a_2
-   libuuid=2.38.1=h0b41bf4_0
-   libwebp-base=1.3.2=h5eee18b_0
-   libxcb=1.15=h7f8727e_0
-   libxcrypt=4.4.36=hd590300_1
-   libxml2=2.12.5=h232c23b_0
-   libxslt=1.1.39=h76b75d6_0
-   libzip=1.10.1=h2629f0a_3
-   libzlib=1.2.13=hd590300_5
-   libzopfli=1.0.3=he6710b0_0
-   lightgbm=3.3.5=py311h6a678d5_0
-   llvm-openmp=17.0.6=h4dfa4b3_0
-   lxml=5.1.0=py311h9691dec_0
-   lz4-c=1.9.4=h6a678d5_0
-   lzo=2.10=h516909a_1000
-   mamba=1.5.1=py311h3072747_2
-   menuinst=2.0.2=py311h38be061_0
-   meson=1.3.1=py311h06a4308_0
-   meson-python=0.15.0=py311h5eee18b_0
-   minizip=4.0.4=h0ab5242_0
-   mkl=2023.1.0=h213fc3f_46344
-   mkl-service=2.4.0=py311h5eee18b_1
-   mkl_fft=1.3.8=py311h5eee18b_0
-   mkl_random=1.2.4=py311hdb19cb5_0
-   ncurses=6.4=h6a678d5_0
-   netcdf4=1.6.5=nompi_py311he8ad708_100
-   networkx=3.1=py311h06a4308_0
-   ninja=1.10.2=h06a4308_5
-   ninja-base=1.10.2=hd09550d_5
-   nspr=4.35=h6a678d5_0
-   nss=3.98=h1d7d5a4_0
-   numexpr=2.8.7=py311h65dcdc2_0
-   numpy=1.23.5=py311h08b1b3b_1
-   numpy-base=1.23.5=py311hf175353_1
-   openjpeg=2.5.2=h488ebb8_0
-   openssl=3.2.1=hd590300_0
-   packaging=23.0=py311h06a4308_0
-   pandas=1.5.3=py311hba01205_0
-   pcre2=10.42=hebb0a14_0
-   pillow=10.2.0=py311ha6c5da5_0
-   pip=23.3.1=py311h06a4308_0
-   pixman=0.43.2=h59595ed_0
-   platformdirs=4.2.0=pyhd8ed1ab_0
-   pluggy=1.0.0=py311h06a4308_1
-   poppler=24.02.0=h590f24d_0
-   poppler-data=0.4.11=h06a4308_1
-   postgresql=16.2=h7387d8b_0
-   proj=9.3.1=he5811b7_0
-   py-cpuinfo=9.0.0=py311h06a4308_0
-   pybind11-abi=4=hd3eb1b0_1
-   pycosat=0.6.4=py311h5eee18b_0
-   pycparser=2.21=pyhd3eb1b0_0
-   pyopenssl=24.0.0=py311h06a4308_0
-   pyparsing=3.0.9=py311h06a4308_0
-   pyproject-metadata=0.7.1=py311h06a4308_0
-   pysocks=1.7.1=py311h06a4308_0
-   pytables=3.9.2=py311h10c7f7f_1
-   pytest=7.4.0=py311h06a4308_0
-   python=3.11.8=hab00c5b_0_cpython
-   python-dateutil=2.8.2=pyhd3eb1b0_0
-   python_abi=3.11=2_cp311
-   pytz=2023.3.post1=py311h06a4308_0
-   rasterio=1.3.9=py311ha38370a_2
-   rav1e=0.6.6=he8a937b_2
-   re2=2023.09.01=h7f4b329_2
-   readline=8.2=h5eee18b_0
-   reproc=14.2.4=h295c915_1
-   reproc-cpp=14.2.4=h295c915_1
-   requests=2.29.0=py311h06a4308_0
-   ruamel.yaml=0.17.21=py311h5eee18b_0
-   s2n=1.4.5=h06160fa_0
-   scikit-image=0.22.0=py311ha02d727_0
-   scikit-learn=1.3.0=py311ha02d727_1
-   scipy=1.11.4=py311h08b1b3b_0
-   setuptools=68.2.2=py311h06a4308_0
-   six=1.16.0=pyhd3eb1b0_1
-   snappy=1.1.10=h6a678d5_1
-   snuggs=1.4.7=pyhd3eb1b0_0
-   sqlite=3.41.2=h5eee18b_0
-   svt-av1=1.8.0=h59595ed_0
-   tbb=2021.8.0=hdb19cb5_0
-   threadpoolctl=2.2.0=pyh0d69192_0
-   tifffile=2023.4.12=py311h06a4308_0
-   tiledb=2.20.1=h6997b71_2
-   tk=8.6.13=noxft_h4845f30_101
-   toolz=0.12.0=py311h06a4308_0
-   tqdm=4.65.0=py311h92b7b1e_0
-   truststore=0.8.0=pyhd8ed1ab_0
-   tzcode=2024a=h3f72095_0
-   tzdata=2023c=h04d1e81_0
-   uriparser=0.9.7=h5eee18b_0
-   urllib3=1.26.16=py311h06a4308_0
-   wheel=0.41.2=py311h06a4308_0
-   xerces-c=3.2.5=hac6953d_0
-   xorg-kbproto=1.0.7=h7f98852_1002
-   xorg-libice=1.1.1=hd590300_0
-   xorg-libsm=1.2.4=h7391055_0
-   xorg-libx11=1.8.7=h8ee46fc_0
-   xorg-libxext=1.3.4=h0b41bf4_2
-   xorg-libxrender=0.9.11=hd590300_0
-   xorg-renderproto=0.11.1=h7f98852_1002
-   xorg-xextproto=7.3.0=h0b41bf4_1003
-   xorg-xproto=7.0.31=h27cfd23_1007
-   xz=5.4.2=h5eee18b_0
-   yaml-cpp=0.8.0=h59595ed_0
-   zfp=1.0.1=h59595ed_0
-   zlib=1.2.13=hd590300_5
-   zlib-ng=2.0.7=h5eee18b_0
-   zstandard=0.19.0=py311h5eee18b_0
-   zstd=1.5.5=hc292b87_0
-   pip:
    -   aenum==3.1.15
    -   anyio==4.3.0
    -   awscli==1.32.55
    -   boto==2.49.0
    -   boto3==1.34.55
    -   botocore==1.34.55
    -   branca==0.7.1
    -   cachetools==5.3.3
    -   cattrs==23.2.3
    -   checksumdir==1.2.0
    -   ciso8601==2.3.1
    -   click-datetime==0.2
    -   colorama==0.4.4
    -   dask==2024.2.1
    -   dataclasses-json==0.6.4
    -   datacube==1.8.17
    -   defusedxml==0.7.1
    -   deprecat==2.1.1
    -   distributed==2024.2.1
    -   docutils==0.16
    -   eodatasets3==0.30.5
    -   ephem==4.1.5
    -   fiona==1.9.5
    -   folium==0.16.0
    -   fsspec==2024.2.0
    -   geoalchemy2==0.14.6
    -   geopandas==0.14.3
    -   greenlet==3.0.3
    -   h11==0.14.0
    -   httpcore==1.0.4
    -   httpx==0.27.0
    -   importlib-metadata==7.0.1
    -   jinja2==3.1.3
    -   jmespath==1.0.1
    -   jsonschema==4.21.1
    -   jsonschema-specifications==2023.12.1
    -   lark==1.1.9
    -   locket==1.0.0
    -   lockfile==0.12.2
    -   luigi==3.5.0
    -   markupsafe==2.1.5
    -   marshmallow==3.21.1
    -   msgpack==1.0.8
    -   mypy-extensions==1.0.0
    -   nested-lookup==0.2.25
    -   oauthlib==3.2.2
    -   opencv-python-headless==4.9.0.80
    -   partd==1.4.1
    -   psutil==5.9.8
    -   psycopg2==2.9.9
    -   pyasn1==0.5.1
    -   pyproj==3.6.1
    -   pystac==1.9.0
    -   python-daemon==3.0.1
    -   python-rapidjson==1.16
    -   pyyaml==6.0.1
    -   referencing==0.33.0
    -   requests-oauthlib==1.3.1
    -   rpds-py==0.18.0
    -   rsa==4.7.2
    -   s2cloudless==1.7.2
    -   s3transfer==0.10.0
    -   sentinelhub==3.10.1
    -   shapely==2.0.3
    -   sniffio==1.3.1
    -   sortedcontainers==2.4.0
    -   sqlalchemy==1.4.52
    -   structlog==24.1.0
    -   tblib==3.0.0
    -   tenacity==8.2.3
    -   tomli==2.0.1
    -   tomli-w==1.0.0
    -   tornado==6.4
    -   typing-extensions==4.10.0
    -   typing-inspect==0.9.0
    -   utm==0.7.0
    -   wrapt==1.16.0
    -   xarray==2024.2.0
    -   xyzservices==2023.10.1
    -   zict==3.0.0
    -   zipp==3.17.0
prefix: /opt/conda
