name: base
channels:
-   conda-forge
-   defaults
dependencies:
-   _libgcc_mutex=0.1=conda_forge
-   _openmp_mutex=4.5=2_kmp_llvm
-   affine=2.3.0=pyhd3eb1b0_0
-   aom=3.6.0=h6a678d5_0
-   attrs=23.1.0=py311h06a4308_0
-   blas=1.0=mkl
-   blosc=1.21.3=h6a678d5_0
-   boltons=23.0.0=py311h06a4308_0
-   boost-cpp=1.81.0=he95ae9e_0
-   bottleneck=1.3.5=py311hbed6279_0
-   brotli=1.0.9=h5eee18b_7
-   brotli-bin=1.0.9=h5eee18b_7
-   brotlipy=0.7.0=py311h5eee18b_1002
-   brunsli=0.1=h2531618_0
-   bzip2=1.0.8=h7b6447c_0
-   c-ares=1.19.0=h5eee18b_0
-   c-blosc2=2.8.0=h6a678d5_0
-   ca-certificates=2023.08.22=h06a4308_0
-   cached-property=1.5.2=py_0
-   cairo=1.16.0=hb05425b_5
-   certifi=2023.7.22=pyhd8ed1ab_0
-   cffi=1.15.1=py311h5eee18b_3
-   cfitsio=4.2.0=hd9d235c_0
-   charls=2.4.2=h59595ed_0
-   charset-normalizer=2.0.4=pyhd3eb1b0_0
-   click=8.0.4=py311h06a4308_0
-   click-plugins=1.1.1=pyhd3eb1b0_0
-   cligj=0.7.2=pyhd3eb1b0_0
-   cloudpickle=2.2.1=py311h06a4308_0
-   conda=23.7.4=py311h38be061_0
-   conda-content-trust=0.2.0=py311h06a4308_0
-   conda-libmamba-solver=23.9.1=py311h06a4308_0
-   conda-package-handling=2.1.0=py311h06a4308_0
-   conda-package-streaming=0.8.0=py311h06a4308_0
-   cryptography=41.0.3=py311hdda0065_0
-   curl=8.2.1=hdbd6064_0
-   cython=3.0.0=py311h5eee18b_0
-   cytoolz=0.12.0=py311h5eee18b_0
-   dask-core=2023.6.0=py311h06a4308_0
-   dav1d=1.2.1=h5eee18b_0
-   expat=2.5.0=h6a678d5_0
-   fmt=10.1.1=h00ab1b0_0
-   fontconfig=2.14.2=h14ed4e7_0
-   freetype=2.12.1=h4a9f257_0
-   freexl=1.0.6=h27cfd23_0
-   fsspec=2023.9.2=py311h06a4308_0
-   gdal=3.6.2=py311hadb6153_4
-   geos=3.11.1=h27087fc_0
-   geotiff=1.7.1=h7a142b4_6
-   giflib=5.2.1=h5eee18b_3
-   glib=2.69.1=he621ea3_2
-   h5py=3.8.0=nompi_py311h1db17ec_100
-   hdf4=4.2.15=h9772cbc_5
-   hdf5=1.12.2=nompi_h4df4325_101
-   hdf5-external-filter-plugins-bitshuffle=0.1.0=h6ca952b_9
-   hdf5plugin=4.1.1=py311hc7375e3_0
-   icu=70.1=h27087fc_0
-   idna=3.4=py311h06a4308_0
-   imagecodecs=2023.1.23=py311ha5a3c35_0
-   imageio=2.31.4=py311h06a4308_0
-   importlib-metadata=6.0.0=py311h06a4308_0
-   iniconfig=1.1.1=pyhd3eb1b0_0
-   intel-openmp=2023.1.0=hdb19cb5_46305
-   joblib=1.2.0=py311h06a4308_0
-   jpeg=9e=h5eee18b_1
-   json-c=0.16=h5eee18b_0
-   jsonpatch=1.32=pyhd3eb1b0_0
-   jsonpointer=2.1=pyhd3eb1b0_0
-   jxrlib=1.1=h7b6447c_2
-   kealib=1.5.0=ha7026e8_0
-   krb5=1.20.1=h143b758_1
-   lazy_loader=0.3=py311h06a4308_0
-   lcms2=2.15=hfd0df8a_0
-   ld_impl_linux-64=2.38=h1181459_1
-   lerc=4.0.0=h27087fc_0
-   libaec=1.1.2=h59595ed_1
-   libarchive=3.6.2=h6ac8c49_2
-   libavif=0.11.1=h5eee18b_0
-   libbrotlicommon=1.0.9=h5eee18b_7
-   libbrotlidec=1.0.9=h5eee18b_7
-   libbrotlienc=1.0.9=h5eee18b_7
-   libcurl=8.2.1=h251f7ec_0
-   libdeflate=1.17=h5eee18b_1
-   libedit=3.1.20221030=h5eee18b_0
-   libev=4.33=h7f8727e_1
-   libexpat=2.5.0=hcb278e6_1
-   libffi=3.4.4=h6a678d5_0
-   libgcc-ng=13.2.0=h807b86a_2
-   libgdal=3.6.2=h13e21a6_4
-   libgfortran-ng=11.2.0=h00389a5_1
-   libgfortran5=11.2.0=h1234567_1
-   libiconv=1.17=h166bdaf_0
-   libkml=1.3.0=h096b73e_7
-   libmamba=1.5.1=h744094f_0
-   libmambapy=1.5.1=py311hf2555c7_0
-   libnetcdf=4.8.1=nompi_h261ec11_106
-   libnghttp2=1.52.0=h2d74bed_1
-   libnsl=2.0.0=h5eee18b_0
-   libpng=1.6.39=h5eee18b_0
-   libpq=15.2=hb675445_0
-   librttopo=1.1.0=ha49c73b_12
-   libsolv=0.7.25=hfc55251_0
-   libspatialite=5.0.1=h221c8f1_23
-   libsqlite=3.43.2=h2797004_0
-   libssh2=1.10.0=hdbd6064_2
-   libstdcxx-ng=13.2.0=h7e041cc_2
-   libtiff=4.5.0=h6adf6a1_2
-   libuuid=2.38.1=h0b41bf4_0
-   libwebp=1.3.2=h11a3e52_0
-   libwebp-base=1.3.2=h5eee18b_0
-   libxcb=1.15=h7f8727e_0
-   libxml2=2.10.3=hca2bb57_4
-   libzip=1.10.1=h2629f0a_3
-   libzlib=1.2.13=hd590300_5
-   libzopfli=1.0.3=he6710b0_0
-   lightgbm=3.3.5=py311h6a678d5_0
-   llvm-openmp=14.0.6=h9e868ea_0
-   locket=1.0.0=py311h06a4308_0
-   lz4-c=1.9.4=h6a678d5_0
-   lzo=2.10=h7b6447c_2
-   mamba=1.5.1=py311h3072747_0
-   meson=1.2.1=py311h06a4308_0
-   meson-python=0.13.1=py311h5eee18b_0
-   mkl=2023.1.0=h213fc3f_46343
-   mkl-service=2.4.0=py311h5eee18b_1
-   mkl_fft=1.3.8=py311h5eee18b_0
-   mkl_random=1.2.4=py311hdb19cb5_0
-   ncurses=6.4=h6a678d5_0
-   networkx=3.1=py311h06a4308_0
-   ninja=1.10.2=h06a4308_5
-   ninja-base=1.10.2=hd09550d_5
-   nspr=4.35=h6a678d5_0
-   nss=3.89.1=h6a678d5_0
-   numexpr=2.8.7=py311h65dcdc2_0
-   numpy=1.23.5=py311h08b1b3b_1
-   numpy-base=1.23.5=py311hf175353_1
-   openjpeg=2.5.0=hfec8fc6_2
-   openssl=3.1.3=hd590300_0
-   packaging=23.0=py311h06a4308_0
-   pandas=1.5.3=py311hba01205_0
-   partd=1.4.0=py311h06a4308_0
-   pcre=8.45=h295c915_0
-   pcre2=10.40=hc3806b6_0
-   pillow=10.0.1=py311ha6cbd5a_0
-   pip=23.2.1=py311h06a4308_0
-   pixman=0.40.0=h7f8727e_1
-   pluggy=1.0.0=py311h06a4308_1
-   poppler=22.12.0=h9614445_3
-   poppler-data=0.4.11=h06a4308_1
-   postgresql=15.2=h3248436_0
-   proj=9.1.1=h8ffa02c_2
-   pybind11-abi=4=hd3eb1b0_1
-   pycosat=0.6.4=py311h5eee18b_0
-   pycparser=2.21=pyhd3eb1b0_0
-   pyopenssl=23.2.0=py311h06a4308_0
-   pyparsing=3.0.9=py311h06a4308_0
-   pyproject-metadata=0.7.1=py311h06a4308_0
-   pysocks=1.7.1=py311h06a4308_0
-   pytables=3.7.0=py311ha8a2728_3
-   pytest=7.4.0=py311h06a4308_0
-   python=3.11.4=hab00c5b_0_cpython
-   python-dateutil=2.8.2=pyhd3eb1b0_0
-   python_abi=3.11=2_cp311
-   pytz=2023.3.post1=py311h06a4308_0
-   pywavelets=1.4.1=py311h5eee18b_0
-   pyyaml=6.0=py311h5eee18b_1
-   rasterio=1.3.6=py311h567e639_0
-   readline=8.2=h5eee18b_0
-   reproc=14.2.4=h295c915_1
-   reproc-cpp=14.2.4=h295c915_1
-   requests=2.29.0=py311h06a4308_0
-   ruamel.yaml=0.17.21=py311h5eee18b_0
-   scikit-image=0.20.0=py311h6a678d5_0
-   scikit-learn=1.3.0=py311ha02d727_0
-   scipy=1.11.3=py311h08b1b3b_0
-   setuptools=68.0.0=py311h06a4308_0
-   six=1.16.0=pyhd3eb1b0_1
-   snappy=1.1.9=h295c915_0
-   snuggs=1.4.7=pyhd3eb1b0_0
-   sqlite=3.41.2=h5eee18b_0
-   tbb=2021.8.0=hdb19cb5_0
-   threadpoolctl=2.2.0=pyh0d69192_0
-   tifffile=2023.4.12=py311h06a4308_0
-   tiledb=2.13.2=hd532e3d_0
-   tk=8.6.12=h1ccaba5_0
-   tomli=2.0.1=py311h06a4308_0
-   toolz=0.12.0=py311h06a4308_0
-   tqdm=4.65.0=py311h92b7b1e_0
-   tzcode=2023c=h0b41bf4_0
-   tzdata=2023c=h04d1e81_0
-   uriparser=0.9.7=h5eee18b_0
-   urllib3=1.26.16=py311h06a4308_0
-   wheel=0.41.2=py311h06a4308_0
-   xerces-c=3.2.4=h55805fa_1
-   xz=5.4.2=h5eee18b_0
-   yaml=0.2.5=h7b6447c_0
-   yaml-cpp=0.7.0=h295c915_1
-   zfp=1.0.0=h6a678d5_0
-   zipp=3.11.0=py311h06a4308_0
-   zlib=1.2.13=hd590300_5
-   zlib-ng=2.0.7=h5eee18b_0
-   zstandard=0.19.0=py311h5eee18b_0
-   zstd=1.5.5=hc292b87_0
-   pip:
    -   aenum==3.1.15
    -   awscli==1.29.63
    -   boto==2.49.0
    -   boto3==1.28.63
    -   botocore==1.31.63
    -   branca==0.6.0
    -   cachetools==5.3.1
    -   cattrs==23.1.2
    -   cftime==1.6.2
    -   checksumdir==1.2.0
    -   ciso8601==2.3.0
    -   click-datetime==0.2
    -   colorama==0.4.4
    -   dataclasses-json==0.6.1
    -   datacube==1.8.15
    -   defusedxml==0.7.1
    -   deprecat==2.1.1
    -   distributed==2023.6.0
    -   docutils==0.16
    -   eodatasets3==0.29.7
    -   ephem==4.1.5
    -   fiona==1.9.5
    -   folium==0.14.0
    -   geoalchemy2==0.14.1
    -   geopandas==0.14.0
    -   greenlet==3.0.0
    -   jinja2==3.1.2
    -   jmespath==1.0.1
    -   jsonschema==4.19.1
    -   jsonschema-specifications==2023.7.1
    -   lark==1.1.7
    -   lockfile==0.12.2
    -   luigi==3.4.0
    -   markupsafe==2.1.3
    -   marshmallow==3.20.1
    -   msgpack==1.0.7
    -   mypy-extensions==1.0.0
    -   nested-lookup==0.2.25
    -   netcdf4==1.6.4
    -   oauthlib==3.2.2
    -   opencv-python-headless==4.8.1.78
    -   psutil==5.9.6
    -   psycopg2==2.9.9
    -   pyasn1==0.5.0
    -   pyproj==3.6.1
    -   pystac==1.8.4
    -   python-daemon==3.0.1
    -   python-rapidjson==1.12
    -   referencing==0.30.2
    -   requests-oauthlib==1.3.1
    -   rpds-py==0.10.6
    -   rsa==4.7.2
    -   s2cloudless==1.7.1
    -   s3transfer==0.7.0
    -   sentinelhub==3.9.1
    -   shapely==2.0.2
    -   sortedcontainers==2.4.0
    -   sqlalchemy==1.4.49
    -   structlog==23.2.0
    -   tblib==2.0.0
    -   tenacity==8.2.3
    -   tomli-w==1.0.0
    -   tornado==6.3.3
    -   typing-extensions==4.8.0
    -   typing-inspect==0.9.0
    -   utm==0.7.0
    -   wrapt==1.15.0
    -   xarray==2023.9.0
    -   zict==3.0.0
prefix: /opt/conda
