name: base
channels:
-   conda-forge
-   defaults
dependencies:
-   affine=2.3.0
-   aom=3.8.1
-   archspec=0.2.3
-   attrs=23.1.0
-   aws-c-auth=0.7.16
-   aws-c-cal=0.6.10
-   aws-c-common=0.9.13
-   aws-c-compression=0.2.18
-   aws-c-event-stream=0.4.2
-   aws-c-http=0.8.1
-   aws-c-io=0.14.5
-   aws-c-mqtt=0.10.2
-   aws-c-s3=0.5.2
-   aws-c-sdkutils=0.1.15
-   aws-checksums=0.1.18
-   aws-crt-cpp=0.26.2
-   aws-sdk-cpp=1.11.267
-   azure-core-cpp=1.11.1
-   azure-storage-blobs-cpp=12.10.0
-   azure-storage-common-cpp=12.5.0
-   blas=1.0
-   blosc=1.21.5
-   boltons=23.0.0
-   boost-cpp=1.82.0
-   bottleneck=1.3.7
-   brotli=1.0.9
-   brotlipy=0.7.0
-   brunsli=0.1
-   bzip2=1.0.8
-   c-ares=1.27.0
-   c-blosc2=2.12.0
-   ca-certificates
-   cached-property=1.5.2
-   cairo=1.18.0
-   certifi
-   cffi=1.15.1
-   cfitsio=4.3.1
-   cftime=1.6.2
-   charls=2.4.2
-   charset-normalizer=2.0.4
-   click=8.1.7
-   click-plugins=1.1.1
-   cligj=0.7.2
-   cloudpickle=2.2.1
-   conda=23.5.2
-   conda-content-trust=0.2.0
-   conda-libmamba-solver=23.7.0
-   conda-package-handling=2.2.0
-   conda-package-streaming=0.9.0
-   cryptography=42.0.2
-   cython=3.0.8
-   dav1d=1.2.1
-   distro=1.9.0
-   expat=2.5.0
-   fmt=10.2.1
-   font-ttf-dejavu-sans-mono=2.37
-   font-ttf-inconsolata=2.001
-   font-ttf-source-code-pro=2.030
-   font-ttf-ubuntu=0.83
-   fontconfig=2.14.2
-   fonts-anaconda=1
-   fonts-conda-ecosystem=1
-   freetype=2.12.1
-   freexl=2.0.0
-   gdal=3.8.4
-   geos=3.12.1
-   geotiff=1.7.1
-   giflib=5.2.1
-   h5py=3.10.0
-   hdf4=4.2.15
-   hdf5=1.14.3
-   hdf5-external-filter-plugins-bitshuffle=0.1.0
-   hdf5plugin=4.4.0
-   icu=73.2
-   idna=3.4
-   imagecodecs=2024.1.1
-   imageio=2.33.1
-   iniconfig=1.1.1
-   intel-openmp=2023.1.0
-   joblib=1.2.0
-   json-c=0.17
-   jsonpatch=1.32
-   jsonpointer=2.1
-   jxrlib=1.1
-   kealib=1.5.3
-   keyutils=1.6.1
-   krb5=1.21.2
-   lazy_loader=0.3
-   lcms2=2.16
-   ld_impl_linux-64=2.38
-   lerc=4.0.0
-   libabseil=20240116.1
-   libaec=1.1.2
-   libarchive=3.7.2
-   libavif16=1.0.4
-   libboost=1.82.0
-   libbrotlicommon=1.1.0
-   libbrotlidec=1.1.0
-   libbrotlienc=1.1.0
-   libcrc32c=1.1.2
-   libcurl=8.5.0
-   libdeflate=1.19
-   libedit=3.1.20221030
-   libev=4.33
-   libexpat=2.5.0
-   libffi=3.4.4
-   libgcc-ng=13.2.0
-   libgdal=3.8.4
-   libgfortran-ng=13.2.0
-   libgfortran5=13.2.0
-   libglib=2.78.4
-   libgoogle-cloud=2.21.0
-   libgoogle-cloud-storage=2.21.0
-   libgrpc=1.61.1
-   libiconv=1.17
-   libjpeg-turbo=3.0.0
-   libkml=1.3.0
-   libmamba=1.5.1
-   libmambapy=1.5.1
-   libnetcdf=4.9.2
-   libnghttp2=1.58.0
-   libnsl=2.0.1
-   libpng=1.6.43
-   libpq=16.2
-   libprotobuf=4.25.2
-   libre2-11=2023.09.01
-   librttopo=1.1.0
-   libsolv=0.7.28
-   libspatialite=5.1.0
-   libsqlite=3.45.1
-   libssh2=1.11.0
-   libstdcxx-ng=13.2.0
-   libtiff=4.6.0
-   libuuid=2.38.1
-   libwebp-base=1.3.2
-   libxcb=1.15
-   libxcrypt=4.4.36
-   libxml2=2.12.5
-   libxslt=1.1.39
-   libzip=1.10.1
-   libzlib=1.2.13
-   libzopfli=1.0.3
-   lightgbm=3.3.5
-   llvm-openmp=17.0.6
-   lxml=5.1.0
-   lz4-c=1.9.4
-   lzo=2.10
-   mamba=1.5.1
-   menuinst=2.0.2
-   meson=1.3.1
-   meson-python=0.15.0
-   minizip=4.0.4
-   mkl=2023.1.0
-   mkl-service=2.4.0
-   mkl_fft=1.3.8
-   mkl_random=1.2.4
-   ncurses=6.4
-   netcdf4=1.6.5
-   networkx=3.1
-   ninja=1.10.2
-   ninja-base=1.10.2
-   nspr=4.35
-   nss=3.98
-   numexpr=2.8.7
-   numpy=1.23.5
-   numpy-base=1.23.5
-   openjpeg=2.5.2
-   openssl=3.2.1
-   packaging=23.0
-   pandas=1.5.3
-   pcre2=10.42
-   pillow=10.2.0
-   pip=23.3.1
-   pixman=0.43.2
-   platformdirs=4.2.0
-   pluggy=1.0.0
-   poppler=24.02.0
-   poppler-data=0.4.11
-   postgresql=16.2
-   proj=9.3.1
-   py-cpuinfo=9.0.0
-   pybind11-abi=4
-   pycosat=0.6.4
-   pycparser=2.21
-   pyopenssl=24.0.0
-   pyparsing=3.0.9
-   pyproject-metadata=0.7.1
-   pysocks=1.7.1
-   pytables=3.9.2
-   pytest=7.4.0
-   python=3.11.8
-   python-dateutil=2.8.2
-   python_abi=3.11
-   pytz=2023.3.post1
-   rasterio=1.3.9
-   rav1e=0.6.6
-   re2=2023.09.01
-   readline=8.2
-   reproc=14.2.4
-   reproc-cpp=14.2.4
-   requests=2.29.0
-   ruamel.yaml=0.17.21
-   s2n=1.4.5
-   scikit-image=0.22.0
-   scikit-learn=1.3.0
-   scipy=1.11.4
-   setuptools=68.2.2
-   six=1.16.0
-   snappy=1.1.10
-   snuggs=1.4.7
-   sqlite=3.41.2
-   svt-av1=1.8.0
-   tbb=2021.8.0
-   threadpoolctl=2.2.0
-   tifffile=2023.4.12
-   tiledb=2.20.1
-   tk=8.6.13
-   toolz=0.12.0
-   tqdm=4.65.0
-   truststore=0.8.0
-   tzcode=2024a
-   tzdata=2023c
-   uriparser=0.9.7
-   urllib3=1.26.16
-   wheel=0.41.2
-   xerces-c=3.2.5
-   xorg-kbproto=1.0.7
-   xorg-libice=1.1.1
-   xorg-libsm=1.2.4
-   xorg-libx11=1.8.7
-   xorg-libxext=1.3.4
-   xorg-libxrender=0.9.11
-   xorg-renderproto=0.11.1
-   xorg-xextproto=7.3.0
-   xorg-xproto=7.0.31
-   xz=5.4.2
-   yaml-cpp=0.8.0
-   zfp=1.0.1
-   zlib=1.2.13
-   zlib-ng=2.0.7
-   zstandard=0.19.0
-   zstd=1.5.5
-   pip:
    -   aenum==3.1.15
    -   anyio==4.3.0
    -   awscli==1.32.55
    -   boto==2.49.0
    -   boto3==1.34.55
    -   botocore==1.34.55
    -   branca==0.7.1
    -   cachetools==5.3.3
    -   cattrs==23.2.3
    -   checksumdir==1.2.0
    -   ciso8601==2.3.1
    -   click-datetime==0.2
    -   colorama==0.4.4
    -   dask==2024.2.1
    -   dataclasses-json==0.6.4
    -   datacube==1.8.17
    -   defusedxml==0.7.1
    -   deprecat==2.1.1
    -   distributed==2024.2.1
    -   docutils==0.16
    -   eodatasets3==0.30.5
    -   ephem==4.1.5
    -   fiona==1.9.5
    -   folium==0.16.0
    -   fsspec==2024.2.0
    -   geoalchemy2==0.14.6
    -   geopandas==0.14.3
    -   greenlet==3.0.3
    -   h11==0.14.0
    -   httpcore==1.0.4
    -   httpx==0.27.0
    -   importlib-metadata==7.0.1
    -   jinja2==3.1.3
    -   jmespath==1.0.1
    -   jsonschema==4.21.1
    -   jsonschema-specifications==2023.12.1
    -   lark==1.1.9
    -   locket==1.0.0
    -   lockfile==0.12.2
    -   luigi==3.5.0
    -   markupsafe==2.1.5
    -   marshmallow==3.21.1
    -   msgpack==1.0.8
    -   mypy-extensions==1.0.0
    -   nested-lookup==0.2.25
    -   oauthlib==3.2.2
    -   opencv-python-headless==4.9.0.80
    -   partd==1.4.1
    -   psutil==5.9.8
    -   psycopg2==2.9.9
    -   pyasn1==0.5.1
    -   pyproj==3.6.1
    -   pystac==1.9.0
    -   python-daemon==3.0.1
    -   python-rapidjson==1.16
    -   pyyaml==6.0.1
    -   referencing==0.33.0
    -   requests-oauthlib==1.3.1
    -   rpds-py==0.18.0
    -   rsa==4.7.2
    -   s2cloudless==1.7.2
    -   s3transfer==0.10.0
    -   sentinelhub==3.10.1
    -   shapely==2.0.3
    -   sniffio==1.3.1
    -   sortedcontainers==2.4.0
    -   sqlalchemy==1.4.52
    -   structlog==24.1.0
    -   tblib==3.0.0
    -   tenacity==8.2.3
    -   tomli==2.0.1
    -   tomli-w==1.0.0
    -   tornado==6.4
    -   typing-extensions==4.10.0
    -   typing-inspect==0.9.0
    -   utm==0.7.0
    -   wrapt==1.16.0
    -   xarray==2024.2.0
    -   xyzservices==2023.10.1
    -   zict==3.0.0
    -   zipp==3.17.0
prefix: /opt/conda
